### ISSUE TITLE
The application crashes randomly

### ISSUE THREAD

**Issue by LiteItOn** [DoctorEenot/DUCOAndroidMiner#10]
Device:
Samsung s6 edge (SM-G925F)
Android 7.0

The app runs for 16-63 hours and suddenly stops working
it just crashes for no reason

**Comment by rom-bar** [comment]
hi!. i got this crash too. and here is the logcat

```
01-16 05:57:31.845 30049 30121 E AndroidRuntime: Process: com.example.duco_miner, PID: 30049
01-16 05:57:31.845 30049 30121 E AndroidRuntime:        at com.example.duco_miner.MiningThread.hexStringToByteArray(MainActivity.java:68)
01-16 05:57:31.845 30049 30121 E AndroidRuntime:        at com.example.duco_miner.MiningThread.run(MainActivity.java:197)
01-16 05:57:31.850  1119  1490 W ActivityTaskManager:   Force finishing activity com.example.duco_miner/.MainActivity
01-16 05:57:31.855  1119  1490 D PowerHalWrapper: <amsBoostResume> last:com.example.duco_miner, next:com.android.launcher3
01-16 05:57:31.865  1119  1490 D PowerHalWrapper: amsBoostNotify pid:1377,activity:com.android.searchlauncher.SearchLauncher, package:com.android.launcher3, mProcessCreatePackcom.example.duco_miner
01-16 05:57:31.867   491   523 I powerd  : [powerd_req] POWER_MSG_NOTIFY_STATE, pc:0, com.example.duco_miner => com.android.launcher3
01-16 05:57:31.939  1119  1214 W InputDispatcher: channel 'feb977f com.example.duco_miner/com.example.duco_miner.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-16 05:57:31.939  1119  1214 E InputDispatcher: channel 'feb977f com.example.duco_miner/com.example.duco_miner.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-16 05:57:31.939  1119  1490 D AutofillSession: handling death of Token{a44a2b5 ActivityRecord{5b4feec u0 com.example.duco_miner/.MainActivity t3724 f}} when saving=false
01-16 05:57:31.939  1119  3814 I WindowManager: WIN DEATH: Window{feb977f u0 com.example.duco_miner/com.example.duco_miner.MainActivity}
01-16 05:57:31.940  1119  3814 W InputDispatcher: Attempted to unregister already unregistered input channel 'feb977f com.example.duco_miner/com.example.duco_miner.MainActivity (server)'
01-16 05:57:31.940  1119  5209 V ActivityManager: Death received in com.android.server.am.ActivityManagerService$AppDeathRecipient@86bfb1c for thread android.os.BinderProxy@24a325, mPid:30049,mApp:ProcessRecord{dd06c8f 30049:com.example.duco_miner/u0a317}
01-16 05:57:31.941   521   567 I BufferQueueProducer: [com.example.duco_miner/com.example.duco_miner.MainActivity#0](this:0x79566ff800,id:1898,api:1,p:30049,c:521) disconnect(P): api 1
01-16 05:57:31.943  1119  5209 I ActivityManager: Process com.example.duco_miner (pid 30049) has died: vis+99 TOP
01-16 05:57:31.974   521   521 I BufferQueue: [com.example.duco_miner/com.example.duco_miner.MainActivity#0](this:0x79566ff800,id:1898,api:1,p:-1,c:-1) ~BufferQueueCore
01-16 05:57:32.015 29640 30142 I StabilityMonitor: [[ParserUtility] ] key word : com.example.duco_miner
01-16 05:57:32.025 29640 30142 I StabilityMonitor: [APRReport] exceptionItem  tag:data_app_crash packageName:com.example.duco_miner versionCode:1 versionName:1.0
```

**Comment by rom-bar** [comment]
i see from log, sometimes Job string will return either "BAD,Please mine on the pool" or "BAD,Incorrect result".

so for workaround i add this check in MainActivity , before `Job.split(",")`
`                if (Job.contains("BAD"))
                    break;`

**Comment by DoctorEenot** [comment]
Hello, if you wish to push that change into main repository feel free to do so, I will be glad to approve it.

**Comment by DoctorEenot** [comment]
> hi!. i got this crash too. and here is the logcat
> 
> ```
> 01-16 05:57:31.845 30049 30121 E AndroidRuntime: Process: com.example.duco_miner, PID: 30049
> 01-16 05:57:31.845 30049 30121 E AndroidRuntime:        at com.example.duco_miner.MiningThread.hexStringToByteArray(MainActivity.java:68)
> 01-16 05:57:31.845 30049 30121 E AndroidRuntime:        at com.example.duco_miner.MiningThread.run(MainActivity.java:197)
> 01-16 05:57:31.850  1119  1490 W ActivityTaskManager:   Force finishing activity com.example.duco_miner/.MainActivity
> 01-16 05:57:31.855  1119  1490 D PowerHalWrapper: <amsBoostResume> last:com.example.duco_miner, next:com.android.launcher3
> 01-16 05:57:31.865  1119  1490 D PowerHalWrapper: amsBoostNotify pid:1377,activity:com.android.searchlauncher.SearchLauncher, package:com.android.launcher3, mProcessCreatePackcom.example.duco_miner
> 01-16 05:57:31.867   491   523 I powerd  : [powerd_req] POWER_MSG_NOTIFY_STATE, pc:0, com.example.duco_miner => com.android.launcher3
> 01-16 05:57:31.939  1119  1214 W InputDispatcher: channel 'feb977f com.example.duco_miner/com.example.duco_miner.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 01-16 05:57:31.939  1119  1214 E InputDispatcher: channel 'feb977f com.example.duco_miner/com.example.duco_miner.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 01-16 05:57:31.939  1119  1490 D AutofillSession: handling death of Token{a44a2b5 ActivityRecord{5b4feec u0 com.example.duco_miner/.MainActivity t3724 f}} when saving=false
> 01-16 05:57:31.939  1119  3814 I WindowManager: WIN DEATH: Window{feb977f u0 com.example.duco_miner/com.example.duco_miner.MainActivity}
> 01-16 05:57:31.940  1119  3814 W InputDispatcher: Attempted to unregister already unregistered input channel 'feb977f com.example.duco_miner/com.example.duco_miner.MainActivity (server)'
> 01-16 05:57:31.940  1119  5209 V ActivityManager: Death received in com.android.server.am.ActivityManagerService$AppDeathRecipient@86bfb1c for thread android.os.BinderProxy@24a325, mPid:30049,mApp:ProcessRecord{dd06c8f 30049:com.example.duco_miner/u0a317}
> 01-16 05:57:31.941   521   567 I BufferQueueProducer: [com.example.duco_miner/com.example.duco_miner.MainActivity#0](this:0x79566ff800,id:1898,api:1,p:30049,c:521) disconnect(P): api 1
> 01-16 05:57:31.943  1119  5209 I ActivityManager: Process com.example.duco_miner (pid 30049) has died: vis+99 TOP
> 01-16 05:57:31.974   521   521 I BufferQueue: [com.example.duco_miner/com.example.duco_miner.MainActivity#0](this:0x79566ff800,id:1898,api:1,p:-1,c:-1) ~BufferQueueCore
> 01-16 05:57:32.015 29640 30142 I StabilityMonitor: [[ParserUtility] ] key word : com.example.duco_miner
> 01-16 05:57:32.025 29640 30142 I StabilityMonitor: [APRReport] exceptionItem  tag:data_app_crash packageName:com.example.duco_miner versionCode:1 versionName:1.0
> ```

Thank you for logs, but unfortunately I have no intensions on continuing development of that miner in the nearest future.
